version: "3.7"
services:
  web:
    build: .
    restart: always
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./
        target: /var/www
    networks:
      fusionauth_net:
        aliases:
          - php
  frontend:
    build: .
    restart: always
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./
        target: /var/www
    networks:
      - fusionauth_net
    command: npm run watch
  nginx:
    image: jguyomard/laravel-nginx:1.13
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /var/www
    networks:
      - fusionauth_net
    ports:
      - 8002:80
networks:
  fusionauth_net:
    external: true
